apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    fingerprint: 12345
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        fingerprint: "12349"
    spec:
      containers:
        - name: web
          image: docker.io/reallymovinggroup/tls-demo:web-d62d9b8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker.io
