# comments

---

name: build
on:
  push:
    branches:
      - 'main'

jobs:

  build_release_candidate:

    name:        Build Container Image
    runs-on:     ubuntu-latest
    permissions: write-all

    steps:

      - name: commit
        id:   commit
        uses: prompt/actions-commit-hash@v3
        with:
          prefix: ""

      - name: set_up_qemu
        id:   set_up_qemu
        uses: docker/setup-qemu-action@v3

      - name: set_up_docker_buildx
        id:   set_up_docker_buildx
        uses: docker/setup-buildx-action@v3

      - name: login_to_docker_hub
        id:   login_to_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build_and_push_web
        id:   build_and_push_web
        uses: docker/build-push-action@v5
        with:
          file: infrastructure/build/Dockerfile.web
          push: true
          tags: reallymovinggroup/tls-demo:web-${{ steps.commit.outputs.short }}

      - name: build_and_push_app
        id:   build_and_push_app
        uses: docker/build-push-action@v5
        with:
          file: infrastructure/build/Dockerfile.app
          push: true
          tags: reallymovinggroup/tls-demo:app-${{ steps.commit.outputs.short }}