# comments

---

name: tag
on:
  push:
    tags: [production-v*]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: commit
        id:   commit
        uses: prompt/actions-commit-hash@v3
        with:
          prefix: ""

      # needed?
      - name: Checkout
        uses: actions/checkout@v2

      - name: login_to_docker_hub
        id:   login_to_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # needed?
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: reallymovinggroup/tls-demo:web-${{ steps.commit.outputs.short }}

      - name: Update the DockerHub Image Tag
        uses: kphrx/docker-buildx-imagetools-action@v0.1.0
        with:
          sources:
            reallymovinggroup/tls-demo:web-${{ steps.commit.outputs.short }}
          tags:
            reallymovinggroup/tls-demo:web-production

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/production',
              sha: context.sha
            })
