# comments

---

name: tag
on:
  push:
    tags: [production-v*]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: commit
        id:   commit
        uses: prompt/actions-commit-hash@v3
        with:
          prefix: ""

      - name: Checkout
        uses: actions/checkout@v2

      - name: login_to_docker_hub
        id:   login_to_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: reallymovinggroup/tls-demo:web-${{ steps.commit.outputs.short }}

      #- name: Build and push the Docker image
      #  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #  with:
      #    context: .
      #    push: true
      #    tags: reallymovinggroup/tls-demo:web-production

      - name: Push Tag
        uses: contiamo/retag-push@main
        with:
          source: reallymovinggroup/tls-demo:web-${{ steps.commit.outputs.short }}
          target: reallymovinggroup/tls-demo:web-production
